### ISSUE TITLE
Unable to manage users

### ISSUE THREAD

**Issue by rascaraficci** [dojot/gui#10]
Access to the AUTH page is not allowed to any user.

The GUI gives the message "You don't have access to this area"

**Comment by mmagr** [comment]
Should be fixed in 0.1.0-dojot-RC2.

**Comment by mmagr** [comment]
This seems to refer to errors prior to release 0.1.0.
Can we close this?

**Comment by mmagr** [comment]
fixed at release [0.1.0-dojot](https://github.com/dojot/docker-compose/releases/tag/0.1.0-dojot).
