### ISSUE TITLE
User creation screen has issues if screen height isn't enough

### ISSUE THREAD

**Issue by ericbaum** [dojot/gui#113]
If the screen height is small, the confirm and abandon button are moved over the other fields. 
It is also not possible to scroll down to look at the fields that are outside the window area. The issue can be seen on the attache image:

![screenshot from 2018-03-26 13-59-02](https://user-images.githubusercontent.com/4474364/37920849-6173e3ce-30fe-11e8-9aba-cde304c1bb8e.png)

**Comment by betefaber** [comment]
Test OK.

![screenshot_32](https://user-images.githubusercontent.com/37310063/45841684-ef6ef780-bcf0-11e8-8190-1298b419455a.png)
