### ISSUE TITLE
Alarms appearance time pattern issue

### ISSUE THREAD

**Issue by ericbaum** [dojot/gui#125]
As can be seen on the attached image, the appearance time for an alarm has the month shown with two characters as a "04" and the day has only one character "2".

I think both the day and the month must be shown with either a 0 on the front or without it.

![screenshot from 2018-04-02 12-43-41](https://user-images.githubusercontent.com/4474364/38202926-db428cd0-3673-11e8-9e40-66c7e1fe5b78.png)

**Comment by hvjunior** [comment]
This page will be re-implemented.

**Comment by cfrancisco** [comment]
The alarm page has been removed.
