### ISSUE TITLE
Buttons become white on flow screen

### ISSUE THREAD

**Issue by ericbaum** [dojot/gui#126]
The buttons for saving and removing on the flow screen gradually become whiter every time they are clicked until they become completely white and unreadable as can be seen on the attached screenshot.

![screenshot from 2018-04-02 13-40-20](https://user-images.githubusercontent.com/4474364/38205064-939cc6f4-367b-11e8-8f48-45f9b6558cb3.png)

**Comment by ericbaum** [comment]
This issue is also valid for the buttons of other windows

**Comment by cfrancisco** [comment]
The buttons were changed.
