### ISSUE TITLE
Simultaneous template creation

### ISSUE THREAD

**Issue by ericbaum** [dojot/gui#127]
If the create template button is clicked multiple times, various template creation gadgets are opened simultaneously. If you click on the create to finish one of then, all the others disappear and also the data that was added to them.

Only one template creation gadget should exist at one point or the other ones that are being created must be kept on the screen when one of them is saved.

![screenshot from 2018-04-02 13-52-56](https://user-images.githubusercontent.com/4474364/38205483-292f86ce-367d-11e8-95f8-08b4448fe317.png)

**Comment by ericbaum** [comment]
This same issue is valid for templates edition. It is possible to edit multiple templates at the same time, but when one of them is saved, the data of all the other templates that were being edited is lost.

**Comment by betefaber** [comment]
This does not happen anymore. Templates screen has been refactored.

![screenshot_32](https://user-images.githubusercontent.com/37310063/50843967-e6ae3a00-1350-11e9-9631-fc78fb5381a6.png)
