### ISSUE TITLE
Template cards in list have different rendering schemes

### ISSUE THREAD

**Issue by mmagr** [dojot/gui#128]
On the device template list, the first two templates on any given row will, when opened, be displayed in one manner:

![image](https://user-images.githubusercontent.com/25080094/38213669-855b41a2-3698-11e8-8f30-2ba1ab8c3e34.png)

Notice that the expanded card takes up a couple of rows, and those are filled with other, collapsed templates.

While the latter two are rendered differently:

![image](https://user-images.githubusercontent.com/25080094/38213957-723fe108-3699-11e8-822b-146acb8fef31.png)

Notice that the expanded card took up the extra rows, but those were left blank (except for the area used for the expanded card)

This was verified on firefox 59.0.1 (64-bit), on a 1080p screen.

**Comment by ericbaum** [comment]
This issue is still happening as it can be seen on the attached screenshot:

![screenshot from 2018-09-11 13-34-10](https://user-images.githubusercontent.com/4474364/45374073-6efd1800-b5c7-11e8-9623-4402e0443f76.png)
