### ISSUE TITLE
Markers in maps have different centre points

### ISSUE THREAD

**Issue by mmagr** [dojot/gui#137]
When tracking for any given device is activated, two new UI elements are added to the map: a smaller set of blue circular pins and a "tracking line", that connects them.

Given that those three elements have different sizes (counting the big "current" circular red pin), it is noticeable that they are not aligned (that is, centralized). Currently they seem to be left- and top-aligned, which gives the user a strange feeling about the accuracy of the data displayed.

![image](https://user-images.githubusercontent.com/25080094/38433572-ca410782-39a1-11e8-95be-4e66f41715c6.png)

**Comment by cfrancisco** [comment]
The tracking mechanism was disabled.
