### ISSUE TITLE
[GUI] User creation - incomprehensible select box

### ISSUE THREAD

**Issue by cfrancisco** [dojot/gui#160]
When tries select a profile for a new user, is showing an incomprehensible select box that blocks the correct visualization of its options.

![Screenshot from 2018-04-27 01-29-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c13020f1fa5c0011f3d876/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd7b468ef13365356424ead53444d04bea6d37ef5f22e7a985902bfd73e0c27c03911faea811bbf01b975df4f81e0b9df5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5af243e14e53a11b3767ee647b.png)

**Comment by betefaber** [comment]
Issue has been fixed.

![image](https://user-images.githubusercontent.com/37310063/42778180-a4a40b44-8912-11e8-87e7-8ff0f32f0d1c.png)
