### ISSUE TITLE
[GUI] User creation - Wrong tooltip for buttons

### ISSUE THREAD

**Issue by cfrancisco** [dojot/gui#162]
When a cursor is positioned over the buttons, is showing a wrong message about the operation.

PS: Is shown the same message for all buttons. 

![Screenshot from 2018-04-27 01-50-27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c13020f1fa5c0011f3d876/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37f3dd7b468ef1336545f424cab53444d04bea6d37ef5f22e7a985902bfd73e0c27c03911faea811bbf01b975df4f81e0b9df5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5af243e14850a0133161ee647b.png)

**Comment by betefaber** [comment]
issue resolved:
![createUser_tooltip.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab121efe0ecea00121e8bc5/125516c66e82c728ace21e0d46eb869f2296869c9cecad7cb052ff983d4f37316546b3397f8fe62bab0021435a561caa120b0c42f8f9df79a5b23c7089095fedd53b5a21d42103eee9dc4be05ce36ade0d97bcae8b44cae93827e288894e3d1c041f8df64f78.png)
