### ISSUE TITLE
Notification toasts has meaningless color

### ISSUE THREAD

**Issue by pedropaulomartucci** [dojot/gui#205]
All the notification toasts has the same color, which makes necessary reading the whole message to known if the action was successful or not.

![image](https://user-images.githubusercontent.com/9469719/40939199-5d71fd1c-681a-11e8-9b75-30de81de384d.png)

![image](https://user-images.githubusercontent.com/9469719/40939248-8068dc82-681a-11e8-8f95-a8ae59a59bad.png)

**Comment by betefaber** [comment]
Issue has been fixed.

![image](https://user-images.githubusercontent.com/37310063/42777965-07b5dd08-8912-11e8-8480-123217397efa.png)

![image](https://user-images.githubusercontent.com/37310063/42777988-14a68616-8912-11e8-964b-eec924d67e8f.png)

![image](https://user-images.githubusercontent.com/37310063/42778004-2232f8b4-8912-11e8-8f6e-26a192fbc7e8.png)

![image](https://user-images.githubusercontent.com/37310063/42777941-f2507cb6-8911-11e8-8e7d-b773142c1e1a.png)

![image](https://user-images.githubusercontent.com/37310063/42777925-e0333f0a-8911-11e8-90ba-13235b9a8707.png)

![image](https://user-images.githubusercontent.com/37310063/42777872-bf226fde-8911-11e8-83b6-2d5dadc95fed.png)

![image](https://user-images.githubusercontent.com/37310063/42777839-a4fe0898-8911-11e8-8d2f-7c6a5420b8f9.png)
