### ISSUE TITLE
Labels are not cleared between the creation of two templates

### ISSUE THREAD

**Issue by ericbaum** [dojot/gui#35]
First, we create a template and associate labels to it, then, if we try to create a second template, the labels that were added to the first template are carried to the new template creation page.

This problems was seen on the 0.2.0-nightly-20171010 build.

**Comment by mmagr** [comment]
:thinking: 

Since that nightly build the template configuration page has been heavily updated.
@hvjunior @ericbaum @cfrancisco Can we close this?

**Comment by hvjunior** [comment]
For me, it's ok!

**Comment by ericbaum** [comment]
We can close this issue
