### ISSUE TITLE
It's not possible to create a flow

### ISSUE THREAD

**Issue by rascaraficci** [dojot/gui#63]
After clicking on the 'New Template' button, it's openned a new page, but it is not possible doing anything. 

![image](https://user-images.githubusercontent.com/31006659/35924831-4b56dae6-0c0b-11e8-9f17-f81f7d6daab8.png)

**Comment by mmagr** [comment]
As part of the effort to improve dojot's current architecture a kafka broker is now used to connect information producers (iotagents and orchestrator services) to information consumers (history and orchestrator services; application).

As a side effect, all code that used to gather information from orion are now "deprecated".
Much of the backporting for those services has been implemented already - but perseo remains to be ported.

Given that perseo itself is to be deprecated in favor of a more modular flow processing engine, its backport has been held back, at least during the development cycle from feb 6th to feb 20th.
In this period, activities related to a first functional implementation of the new flow processing engine are to take place. This new processing engine shall be compatible with the kafka-centered architecture.

The aforementioned activities are as follows:
- dojot/dojot#211
- dojot/dojot#212
- dojot/dojot#213
- dojot/dojot#214
- dojot/dojot#215

As soon as those are done, a new nightly build will be generated for dojot, and flow configuration should become available for usage once more.

**Comment by rascaraficci** [comment]
The nodes are available and it is possible to use them to create flows.
